### PR TITLE
Add microservice deployment instructions

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/31)

### CODE REVIEW

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/31)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[README.md, line 270 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-Miz6vlgC32FKyaJdhYP:-Miz6vlgC32FKyaJdhYQ:bgskr0g) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/7e55992b2010bae8afea3d2f398fc3b97ff49781/README.md#L270)):*
> ```Markdown
> 1. Describe the new microservice in `generate/values/common.yaml`. For reference, see how other
>    microservices are created
> 1. Create a new service manifest in `generate/templates/kubernetes-all`. If you don't need anything
> ```

In fact you can't just copypaste the file as they contain service name. Maybe you should mention also that. Something like: ... you could just copy-paste the themplate from another microservice *and rename relevant parts* 
___
*[README.md, line 272 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-Miz7JQf3hwM5DbVwzM0:-Miz7JQg0HtQFUxRu2x4:b-wbbqv4) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/7e55992b2010bae8afea3d2f398fc3b97ff49781/README.md#L272)):*
> ```Markdown
> 1. Create a new service manifest in `generate/templates/kubernetes-all`. If you don't need anything
>    custom additions, you could just copy-paste the template from another microservice
> 1. If needed, create the ingress rule and other environment-specific customizations in
> ```

What is ingress rule, when there is need for that or is that common knowledge for everyone?
___
*[README.md, line 277 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-Miz7mTA6QN61PK0PrUd:-Miz7mTA6QN61PK0PrUe:bl2rh80) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/7e55992b2010bae8afea3d2f398fc3b97ff49781/README.md#L277)):*
> ```Markdown
> 1. Test that everything works:
>    a) with docker-compose: `docker-compose -f clusters/docker-compose.yaml up`
>    b) with Kind: `./kindcluster start --cluster=clusters/e2e`
> ```

Does this have to be e2e cluster or can it be any cluster?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/31)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[README.md, line 270 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-Miz6vlgC32FKyaJdhYP:-MizZyfdC9ZsPgxQciDC:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/7e55992b2010bae8afea3d2f398fc3b97ff49781/README.md#L270)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

In fact you can't just copypaste the file as they contain service name. Maybe you should mention also that. Something like: ... you could just copy-paste the themplate from another microservice *and rename relevant parts* 
</blockquote></details>

Done.
___
*[README.md, line 272 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-Miz7JQf3hwM5DbVwzM0:-Miz_Yw6Dz3h8r1Zrgau:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/7e55992b2010bae8afea3d2f398fc3b97ff49781/README.md#L272)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

What is ingress rule, when there is need for that or is that common knowledge for everyone?
</blockquote></details>

Done.
___
*[README.md, line 277 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-Miz7mTA6QN61PK0PrUd:-Miz__4M401ks9CYzdpB:b-c595nr) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/7e55992b2010bae8afea3d2f398fc3b97ff49781/README.md#L277)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Does this have to be e2e cluster or can it be any cluster?
</blockquote></details>

currently can only run the e2e cluster in Kind, because only that one has proper ingress defined

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/31)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[README.md, line 277 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-Miz7mTA6QN61PK0PrUd:-Mizi9ZvEt3O6PoELb-k:b-97zn9v) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/7e55992b2010bae8afea3d2f398fc3b97ff49781/README.md#L277)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

currently can only run the e2e cluster in Kind, because only that one has proper ingress defined
</blockquote></details>

Should we mention that? But ok, that is fine for me.
___
*[README.md, line 276 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-Miz_vOFAOFRXlvK_Hbt:-Miz_vOFAOFRXlvK_Hbu:b-3cjzhd) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/40f5402f7248a0f8920340eb6e7dbf922ca7650c/README.md#L276)):*
> ```Markdown
> 1. Generate the manifests using `./development.sh generate`
> 1. Test locally that everything works:
>    1. with docker-compose: `docker-compose -f clusters/docker-compose.yaml up`
> ```

`docker-compose -f clusters/docker-compose/docker-compose.yml up`
(one directory missing, yml instead of yaml)
___
*[README.md, line 280 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-MizgDxm0EPAp0QA57N2:-MizgDxn2beP87GWWDzN:b8coqli) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/68565c2c97fb1044096be2eed9e445c28338f277/README.md#L280)):*
> ```
> /kindcluster start --cluster=clusters/e2e
> ```
`./kindcluster.sh start --cluster=clusters/e2e` (.sh missing)
___
*[README.md, line 283 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-Mizhity0eaJYjUOGDKd:-Mizhity0eaJYjUOGDKe:b4e1pmq) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/68565c2c97fb1044096be2eed9e445c28338f277/README.md#L283)):*
> ```Markdown
>    1. with Azure: commit your changes, move `playg` branch to your the commit and wait for Flux to
>       deploy it for you
> 1. Testing with CI/CD:
> ```

I don't understand these.
1. `remotecluster.sh` doesn't mention word "allow" even once. Which docker image I want to override and why?
2. how should I run github workflow locally? Why CI pipeline won't do this for me?
3. same as 2.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/31)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[README.md, line 276 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-Miz_vOFAOFRXlvK_Hbt:-Miziz634sbYYTXPd09a:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/40f5402f7248a0f8920340eb6e7dbf922ca7650c/README.md#L276)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`docker-compose -f clusters/docker-compose/docker-compose.yml up`
(one directory missing, yml instead of yaml)
</blockquote></details>

Done.
___
*[README.md, line 280 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-MizgDxm0EPAp0QA57N2:-MiziyZt228GPYaV7Z0Y:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/68565c2c97fb1044096be2eed9e445c28338f277/README.md#L280)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

> ```
> /kindcluster start --cluster=clusters/e2e
> ```
`./kindcluster.sh start --cluster=clusters/e2e` (.sh missing)
</blockquote></details>

Done.
___
*[README.md, line 283 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-Mizhity0eaJYjUOGDKd:-MizlwElC5MEnohAiEpi:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/68565c2c97fb1044096be2eed9e445c28338f277/README.md#L283)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I don't understand these.
1. `remotecluster.sh` doesn't mention word "allow" even once. Which docker image I want to override and why?
2. how should I run github workflow locally? Why CI pipeline won't do this for me?
3. same as 2.
</blockquote></details>

Done.

**Review by tk-vincit — APPROVED** [review]
One possible typo. Otherwise approved.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-:-MizqPAu8ZBr0KuXzLdl:b3pylj9)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[README.md, line 285 at r7](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-MizqBsZ9GW1pOU2FqJx:-MizqBsZ9GW1pOU2FqJy:b-3p3vpo) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/4f9b27a735753ed98e06903a3aa7173d9c5eb457/README.md#L285)):*
> ```Markdown
> 1. Testing with CI/CD:
>    1. Kind cluster remote setup: extend the `patchesStrategicMerge` section in `/remotecluster.sh`
>       to allow switching the docker image to another one e2e tests.
> ```

to another one _in_ e2e tests?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/31)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

___
*[README.md, line 285 at r7](https://reviewable.io/reviews/hsldevcom/jore4-flux/31#-MizqBsZ9GW1pOU2FqJx:-Mj-4oD0ET6Y75N6aurk:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/4f9b27a735753ed98e06903a3aa7173d9c5eb457/README.md#L285)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

to another one _in_ e2e tests?
</blockquote></details>

Done.

**Pull request merged**
