### PR TITLE
Set up hasura in Kind and Azure

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/17)

Closes https://github.com/HSLdevcom/jore4/issues/352

### CODE REVIEW

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 40 of 40 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/17)* status: all files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[clusters/e2e/jore4-ingress-patch.yaml, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-McDUZjf6k2zw2OgKQ2_:-McDUZjf6k2zw2OgKQ2a:b-4s0ry9) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/2314a9b9431c09460d4b69e6da101d0e8e9cd4f9/clusters/e2e/jore4-ingress-patch.yaml#L20)):*
> ```
> will an
> ```

"will be an"?

**Review by haphut — COMMENTED** [review]
Nice! :muscle: 

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-:-McE7rEH7Ex_IVRvTwnI:bcp9828)* status: all files reviewed, 5 unresolved discussions (waiting on @pallost)

___
*[.github/workflows/test-e2e-cluster-setup.yml, line 39 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-McDycvP5DWyWsg0XnPT:-McDycvQ3kQ3ypw9PYuo:bp0klff) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0a704f9e9f51fb1dc95780aede16ce63fe681575/.github/workflows/test-e2e-cluster-setup.yml#L39)):*
> ```YAML
>         run: |
>           for i in {1..20}; do
>             curl --fail http://localhost:3300/graphql/console --output /dev/null --silent && break
> ```

Would it make sense to use `/healthz` here and below as well?
___
*[clusters/base/jore4-services/jore4-hasura.yaml, line 46 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-McE-MAoAPXIK4_t8Chi:-McE-MAoAPXIK4_t8Chj:biz24ay) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0a704f9e9f51fb1dc95780aede16ce63fe681575/clusters/base/jore4-services/jore4-hasura.yaml#L46)):*
> ```YAML
>           livenessProbe:
>             httpGet:
>               path: /healthz
> ```

Nice that you have these both.

Detail: I was not sure whether to use `/healthz` or GraphQL schema introspection for probes. I tested locally with `docker-compose` that 7 seconds after the migrations get finished and the GraphQL schema introspection succeeds, `/healthz` returns `200 OK`. So I think even with migrations using `/healthz` is safer than using introspection.

But Hasura sends `200 OK` for complete success and `200 WARN: ...` if it can serve some requests but notices inconsistent/outdated metadata. The latter happens especially if the database schemas partially conflict with the metadata.

I think as our team controls both the SQL migrations and Hasura, we should fail if we get something else than `200 OK`. What do you think? (Reference: https://hasura.io/docs/latest/graphql/core/api-reference/health.html#response )
___
*[clusters/dev/jore4-env-patch.yaml, line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-McE3jep8RlOIr41IaIB:-McE3jep8RlOIr41IaIC:b-5jzz3y) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0a704f9e9f51fb1dc95780aede16ce63fe681575/clusters/dev/jore4-env-patch.yaml#L9)):*
> ```YAML
>   namespace: hsl-jore4
> data:
>   HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
> ```

I'd like to see this difference in the attack surface of `dev` documented somewhere. If someone can break the admin UI somehow so that they get Hasura admin access without knowing the admin secret, they have read+write access to everywhere where Hasura has.

Maybe we need to pay special attention to logs about the  Hasura `console` once we set up alerting. Maybe the console will be useful for debugging, though.
___
*[clusters/e2e/jore4-ingress-patch.yaml, line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-McE6wpxBcQhUYb0jcJm:-McE6wpxBcQhUYb0jcJn:bwuxk1i) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0a704f9e9f51fb1dc95780aede16ce63fe681575/clusters/e2e/jore4-ingress-patch.yaml#L13)):*
> ```YAML
>     kubernetes.io/ingress.class: nginx
>     # rewrite url to regex capture group no 2
>     nginx.ingress.kubernetes.io/rewrite-target: /$2
> ```

Nifty!

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/17)* status: 0 of 40 files reviewed, 5 unresolved discussions (waiting on @haphut and @lassemaatta)

___
*[.github/workflows/test-e2e-cluster-setup.yml, line 39 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-McDycvP5DWyWsg0XnPT:-McEHBLyE7vMNBvNb2A_:blf0tg3) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0a704f9e9f51fb1dc95780aede16ce63fe681575/.github/workflows/test-e2e-cluster-setup.yml#L39)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Would it make sense to use `/healthz` here and below as well?
</blockquote></details>

sure, that'd work too
___
*[clusters/base/jore4-services/jore4-hasura.yaml, line 46 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-McE-MAoAPXIK4_t8Chi:-McEI6Cb4oGfFZIF7Hnu:b4br1w2) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0a704f9e9f51fb1dc95780aede16ce63fe681575/clusters/base/jore4-services/jore4-hasura.yaml#L46)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Nice that you have these both.

Detail: I was not sure whether to use `/healthz` or GraphQL schema introspection for probes. I tested locally with `docker-compose` that 7 seconds after the migrations get finished and the GraphQL schema introspection succeeds, `/healthz` returns `200 OK`. So I think even with migrations using `/healthz` is safer than using introspection.

But Hasura sends `200 OK` for complete success and `200 WARN: ...` if it can serve some requests but notices inconsistent/outdated metadata. The latter happens especially if the database schemas partially conflict with the metadata.

I think as our team controls both the SQL migrations and Hasura, we should fail if we get something else than `200 OK`. What do you think? (Reference: https://hasura.io/docs/latest/graphql/core/api-reference/health.html#response )
</blockquote></details>

It's a good idea but it does not seem to be a trivial change. I don't want to pull this task into scope of this pull request, so let's continue it as its own task. I see you've already created an issue about this: https://github.com/HSLdevcom/jore4/issues/324 Let's move it to the backlog, shall we?
___
*[clusters/dev/jore4-env-patch.yaml, line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-McE3jep8RlOIr41IaIB:-McEIjSAEASSo0hncp_s:b-qwa1mr) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0a704f9e9f51fb1dc95780aede16ce63fe681575/clusters/dev/jore4-env-patch.yaml#L9)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

I'd like to see this difference in the attack surface of `dev` documented somewhere. If someone can break the admin UI somehow so that they get Hasura admin access without knowing the admin secret, they have read+write access to everywhere where Hasura has.

Maybe we need to pay special attention to logs about the  Hasura `console` once we set up alerting. Maybe the console will be useful for debugging, though.
</blockquote></details>

I could just disable the console, this was for testing the environment variable overwrites. But if you have concerns on security, I'll just disable it
___
*[clusters/e2e/jore4-ingress-patch.yaml, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-McDUZjf6k2zw2OgKQ2_:-McEJCnf8JzSJgH0xGg9:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/2314a9b9431c09460d4b69e6da101d0e8e9cd4f9/clusters/e2e/jore4-ingress-patch.yaml#L20)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> will an
> ```

"will be an"?
</blockquote></details>

Done.
___
*[clusters/e2e/jore4-ingress-patch.yaml, line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-McE6wpxBcQhUYb0jcJm:-McEJ52z9TtwLIrMJBWB:b-nilrw) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0a704f9e9f51fb1dc95780aede16ce63fe681575/clusters/e2e/jore4-ingress-patch.yaml#L13)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Nifty!
</blockquote></details>

this seems to be the only way to do it... :grimacing:

**Review by haphut — APPROVED** [review]
> Reviewed 39 of 40 files at r1, 1 of 1 files at r2, 3 of 40 files at r3, 3 of 40 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/17)* status: 3 of 40 files reviewed, 3 unresolved discussions (waiting on @haphut, @lassemaatta, and @pallost)

___
*[clusters/base/jore4-services/jore4-hasura.yaml, line 46 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-McE-MAoAPXIK4_t8Chi:-McEd-m7-2_UdQS_LoNs:bntt0l6) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0a704f9e9f51fb1dc95780aede16ce63fe681575/clusters/base/jore4-services/jore4-hasura.yaml#L46)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

It's a good idea but it does not seem to be a trivial change. I don't want to pull this task into scope of this pull request, so let's continue it as its own task. I see you've already created an issue about this: https://github.com/HSLdevcom/jore4/issues/324 Let's move it to the backlog, shall we?
</blockquote></details>

Yep, that's fine.
___
*[clusters/dev/jore4-env-patch.yaml, line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-McE3jep8RlOIr41IaIB:-McEdIkC1Stvw3Cn5nrV:bwmz4g7) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0a704f9e9f51fb1dc95780aede16ce63fe681575/clusters/dev/jore4-env-patch.yaml#L9)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I could just disable the console, this was for testing the environment variable overwrites. But if you have concerns on security, I'll just disable it
</blockquote></details>

I would disable it until it's needed again. Up to you.
___
*[clusters/e2e/jore4-ingress-patch.yaml, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/17#-McDUZjf6k2zw2OgKQ2_:-McEe0Wz140ECIdXDWcI:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/2314a9b9431c09460d4b69e6da101d0e8e9cd4f9/clusters/e2e/jore4-ingress-patch.yaml#L20)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK

**Pull request merged**
