### PR TITLE
Setting up e2e cluster remotely

### PR DESCRIPTION
**Pull request by pallost**
Closes https://github.com/HSLdevcom/jore4/issues/311

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/11)

### CODE REVIEW

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/11)* status: all files reviewed, 1 unresolved discussion (waiting on @haphut, @jpeuralinna, @jschummer, and @pallost)

___
*[README.md, line 380 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/11#-MaT0luz0puql4n3TMik:-MaT0lv-54TJYq1KCHN9:bicdysm) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/a274c7079faab8755003b82a46403f90b0712ab7/README.md#L380)):*
> ```Markdown
> curl https://raw.githubusercontent.com/HSLdevcom/jore4-flux/e2e/remotecluster.sh | bash
> ```
> ```

Should/can we provide some cleanup instructions as well? 

For example: how can I stop (or later restart) the cluster? How can I remove all traces of the remote cluster if I decide I don't need it anymore? How can I recreate the cluster if `remoteCluster.sh` gets a new version (e.g. some new backend service)?

I think my questions arise because I don't really understand how this works or what this does :)

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/11)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @haphut, @jpeuralinna, @jschummer, and @lassemaatta)

___
*[README.md, line 380 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/11#-MaT0luz0puql4n3TMik:-MaT7RpiCDUcI19ETkC8:b3kez4c) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/a274c7079faab8755003b82a46403f90b0712ab7/README.md#L380)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Should/can we provide some cleanup instructions as well? 

For example: how can I stop (or later restart) the cluster? How can I remove all traces of the remote cluster if I decide I don't need it anymore? How can I recreate the cluster if `remoteCluster.sh` gets a new version (e.g. some new backend service)?

I think my questions arise because I don't really understand how this works or what this does :)
</blockquote></details>

Good catch, I added instructions on stopping the kind cluster and development instructions. Hopefully it's clearer now :)

**Review by lassemaatta — COMMENTED** [review]
Looks ok to me, but perhaps someone else should also check this out.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/11#-:-MaT9KJh2iyEqptP3Eld:b-3di4on)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haphut, @jpeuralinna, and @jschummer)

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/11)* status: all files reviewed, 1 unresolved discussion (waiting on @haphut, @jpeuralinna, @jschummer, and @pallost)

___
*[remotecluster.sh, line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/11#-MaYF3m21zLEseOeZA3v:-MaYF3m21zLEseOeZA3w:b5uv6x6) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/035dbb3442310865c01da4fe3e718136d0fbbd78/remotecluster.sh#L20)):*
> ```Shell
> echo "Downloading helper script"
> curl https://raw.githubusercontent.com/HSLdevcom/jore4-flux/$E2E_SCRIPTS_VERSION/kindcluster.sh --output "$tmp_dir/kindcluster.sh"
> chmod +x "$tmp_dir/kindcluster.sh"
> ```

Why +x flag is not already included in downloaded file?

Would `chmod u+x` be enough?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/11)* status: all files reviewed, 1 unresolved discussion (waiting on @haphut, @jpeuralinna, @jschummer, and @tk-vincit)

___
*[remotecluster.sh, line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/11#-MaYF3m21zLEseOeZA3v:-MaYO3sF6f555KwhG3_k:b-erxoyf) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/035dbb3442310865c01da4fe3e718136d0fbbd78/remotecluster.sh#L20)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why +x flag is not already included in downloaded file?

Would `chmod u+x` be enough?
</blockquote></details>

curl only downloads the raw data, it cannot know that the file is an executable. I fixed the run permission to be u+x as you requested, but this is only a temporary file that gets anyway automatically deleted after the script is run.

**Review by jschummer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/11)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @haphut, @jpeuralinna, @lassemaatta, @pallost, and @tk-vincit)

___
*[README.md, line 368 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/11#-MaYQRuT5NpWJmRjn5YM:-MaYQRuU9OyagvrAMBaY:bckwse8) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/035dbb3442310865c01da4fe3e718136d0fbbd78/README.md#L368)):*
> ```
> remotely
> ```
🤔 What's the remote part? Where is it deployed remotely?

Not sure if I'm missing out on something essential, but maybe you could write a few words about that..
___
*[README.md, line 382 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/11#-MaYLnTpBLivbb5p9N8t:-MaYLnTpBLivbb5p9N8u:b58th57) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/035dbb3442310865c01da4fe3e718136d0fbbd78/README.md#L382)):*
> ```
>  take 
> ```
"take" away? ;-)
___
*[remotecluster.sh, line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/11#-MaYMkiK0Q956a-MpotG:-MaYMkiK0Q956a-MpotH:b-xp9i0x) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/035dbb3442310865c01da4fe3e718136d0fbbd78/remotecluster.sh#L33)):*
<details><summary><i alt="summary">Quoted 32 lines of code…</i></summary>

> ```
> cat <<EOT >"$tmp_dir/kustomization.yaml"
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> resources:
>   # have to use the go-getter url format: https://github.com/hashicorp/go-getter#url-format
>   - github.com/HSLdevcom/jore4-flux/clusters/e2e?ref=$E2E_SCRIPTS_VERSION
> patchesStrategicMerge:
> - |-
>   apiVersion: apps/v1
>   kind: Deployment
>   metadata:
>     name: jore4-frontend
>     namespace: hsl-jore4
>   spec:
>     template:
>       spec:
>         containers:
>         - name: jore4-frontend-image
>           ${FRONTEND_DOCKER_IMAGE:+image: $FRONTEND_DOCKER_IMAGE}
> - |-
>   apiVersion: apps/v1
>   kind: Deployment
>   metadata:
>     name: jore4-backend
>     namespace: hsl-jore4
>   spec:
>     template:
>       spec:
>         containers:
>         - name: jore4-backend-image
>           ${BACKEND_DOCKER_IMAGE:+image: $BACKEND_DOCKER_IMAGE}
> EOT
> ```
</details>


Would it be feasible to have this as its own template file which can be parametrized (using sed, if no other possibilities)?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/11)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @haphut, @jpeuralinna, @jschummer, @lassemaatta, and @tk-vincit)

___
*[README.md, line 368 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/11#-MaYQRuT5NpWJmRjn5YM:-Mb146LH1v8YRDCox-jj:b-ctcsse) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/035dbb3442310865c01da4fe3e718136d0fbbd78/README.md#L368)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> remotely
> ```
🤔 What's the remote part? Where is it deployed remotely?

Not sure if I'm missing out on something essential, but maybe you could write a few words about that..
</blockquote></details>

I wrote a clarifying section that "remote" means "anywhere but your local workdir"
___
*[README.md, line 382 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/11#-MaYLnTpBLivbb5p9N8t:-Mb14I4LDyCv7JQhwurE:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/035dbb3442310865c01da4fe3e718136d0fbbd78/README.md#L382)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
>  take 
> ```
"take" away? ;-)
</blockquote></details>

Done.
___
*[remotecluster.sh, line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/11#-MaYMkiK0Q956a-MpotG:-MacCLylCAcfJmo988p8:b4hoj66) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/035dbb3442310865c01da4fe3e718136d0fbbd78/remotecluster.sh#L33)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> cat <<EOT >"$tmp_dir/kustomization.yaml"
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> resources:
>   # have to use the go-getter url format: https://github.com/hashicorp/go-getter#url-format
>   - github.com/HSLdevcom/jore4-flux/clusters/e2e?ref=$E2E_SCRIPTS_VERSION
> patchesStrategicMerge:
> - |-
>   apiVersion: apps/v1
>   kind: Deployment
>   metadata:
>     name: jore4-frontend
>     namespace: hsl-jore4
>   spec:
>     template:
>       spec:
>         containers:
>         - name: jore4-frontend-image
>           ${FRONTEND_DOCKER_IMAGE:+image: $FRONTEND_DOCKER_IMAGE}
> - |-
>   apiVersion: apps/v1
>   kind: Deployment
>   metadata:
>     name: jore4-backend
>     namespace: hsl-jore4
>   spec:
>     template:
>       spec:
>         containers:
>         - name: jore4-backend-image
>           ${BACKEND_DOCKER_IMAGE:+image: $BACKEND_DOCKER_IMAGE}
> EOT
> ```

Would it be feasible to have this as its own template file which can be parametrized (using sed, if no other possibilities)?
</blockquote></details>

It's a major hassle to try to extract this to its own file. I was investigating `envsubst` to do the importing, but it doesn't handle shell default values. The other option that would work is `yq`, but that also needs quite some tweaking. Kustomize's images transformer (https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/images/) might be an option, but it cannot replace an image using the container name, it can only search for an image to be replaced by the image name... Let's go with this for now and find a solution later when we can find some nice alternative

**Review by jschummer — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/11)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @haphut, @jpeuralinna, @lassemaatta, and @tk-vincit)

___
*[remotecluster.sh, line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/11#-MaYMkiK0Q956a-MpotG:-Mb5Jpj89_g-JgFMKdQU:byg2pi7) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/035dbb3442310865c01da4fe3e718136d0fbbd78/remotecluster.sh#L33)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

It's a major hassle to try to extract this to its own file. I was investigating `envsubst` to do the importing, but it doesn't handle shell default values. The other option that would work is `yq`, but that also needs quite some tweaking. Kustomize's images transformer (https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/images/) might be an option, but it cannot replace an image using the container name, it can only search for an image to be replaced by the image name... Let's go with this for now and find a solution later when we can find some nice alternative
</blockquote></details>

Yes, this is fine. After all, the file is still readable even though it's embedded in the code.

**Review by lassemaatta — COMMENTED** [review]
Still looks ok.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/11#-:-Mb5lTz9C6UQGmyqNNah:b-wn7glz)* status: all files reviewed, 1 unresolved discussion (waiting on @haphut, @jpeuralinna, and @tk-vincit)

**Pull request merged**
