### PR TITLE
Set up e2e cluster in Kind

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/5)

### CODE REVIEW

**Review by lassemaatta — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/5)* status: all files reviewed, 3 unresolved discussions (waiting on @jpeuralinna, @jschummer, and @pallost)

___
*[kubernetes.sh, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-MZSkkuEAOXfFS0ocbvj:-MZSkkuEAOXfFS0ocbvk:bp3ry0x) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/d6d52d39c858746ae5a777289330736885dd0333/kubernetes.sh#L12)):*
> ```Shell
>     param="${KEY/--/}"
>     declare "$param"="$VALUE"
>   fi
> ```

I'd prefer a more strict argument parsing (e.g. `getopts`) instead of offering an open "replace any env with any value" interface. Is this feature needed only for the `--kindconfig` thing below or for something else too?
___
*[kubernetes.sh, line 47 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-MZSlZN425xaANuutFZU:-MZSlZN425xaANuutFZV:b-89s5jz) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/d6d52d39c858746ae5a777289330736885dd0333/kubernetes.sh#L47)):*
> ```
> master
> ```
Could we refer to a specific tag/hash instead of whatever happens to be in `master`?
___
*[kubernetes.sh, line 75 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-MZSohjtE0C4Dm92kAb-:-MZSohjtE0C4Dm92kAb0:b-pz2h30) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/d6d52d39c858746ae5a777289330736885dd0333/kubernetes.sh#L75)):*
> ```
> AZURE_STAGES=("playg" "dev" "test" "prod")
> ```

If we need to list these, then perhaps we could also be explicit with`KIND_STAGES=("e2e")`? And then throw an error if we encounter an unexpected stage? I like things to be explicit rather than implicit and it helps to understand this script if the inputs are well-defined.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/5)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @jpeuralinna, @jschummer, and @lassemaatta)

___
*[kubernetes.sh, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-MZSkkuEAOXfFS0ocbvj:-MZXefi0CVMJPRdbezOq:b-7cc4jz) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/d6d52d39c858746ae5a777289330736885dd0333/kubernetes.sh#L12)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I'd prefer a more strict argument parsing (e.g. `getopts`) instead of offering an open "replace any env with any value" interface. Is this feature needed only for the `--kindconfig` thing below or for something else too?
</blockquote></details>

this is only for parsing `--kindconfig`. I'll change this a bit not to write directly to env variables. The solutions I've seen for `getopts` are tad bit overkill for this simple task here :) 
___
*[kubernetes.sh, line 47 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-MZSlZN425xaANuutFZU:-MZXfDQvDcJIYKEunFIX:b-y0haer) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/d6d52d39c858746ae5a777289330736885dd0333/kubernetes.sh#L47)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> master
> ```
Could we refer to a specific tag/hash instead of whatever happens to be in `master`?
</blockquote></details>

this is what the Kind documentation uses... but I could change this to be commit-specific, true
___
*[kubernetes.sh, line 75 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-MZSohjtE0C4Dm92kAb-:-MZXk-cK4FlRuNwhtR3x:bb7f2mf) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/d6d52d39c858746ae5a777289330736885dd0333/kubernetes.sh#L75)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> AZURE_STAGES=("playg" "dev" "test" "prod")
> ```

If we need to list these, then perhaps we could also be explicit with`KIND_STAGES=("e2e")`? And then throw an error if we encounter an unexpected stage? I like things to be explicit rather than implicit and it helps to understand this script if the inputs are well-defined.
</blockquote></details>

done

**Review by lassemaatta — APPROVED** [review]
Looks ok to me, but perhaps @jschummer should check this out too.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-:-MZkiyarBHKBXDLDnZaM:b-2kda1b)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jpeuralinna and @jschummer)

**Review by jschummer — CHANGES_REQUESTED** [review]
Could you still also take a look at the linter (indentation?) errors?

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-:-MZx-o1z-vqurNzCwU0B:b-hpq77s)* status: all files reviewed, 3 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[kubernetes.sh, line 2 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-MZx-G6-CslCactMJEq9:-MZx-G6-CslCactMJEqA:bqkgk21) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6b33296abd83027a861d19de94329783aa9a67d0/kubernetes.sh#L2)):*
> ```Shell
> #!/bin/bash
> ```

Reading through this a second time, I'm starting to wonder if the local (kind) and Azure setups have enough in common to justify handling both in this same script.

Would it be an option to have the kind stuff all in a separate script?
___
*[kubernetes.sh, line 64 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-MZwz_TG2hAEPFQEoWtz:-MZwz_TG2hAEPFQEoWu-:btd0raq) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6b33296abd83027a861d19de94329783aa9a67d0/kubernetes.sh#L64)):*
> ```
> https://raw.githubusercontent.com/kubernetes/ingress-nginx/ed5aee7659bdd9a5f018ef56ddd2de664b2d96e7/deploy/static/provider/kind/deploy.yaml
> ```
Could this be put in a constant?
___
*[README.md, line 356 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-MZw_g_l55vidlaal-BV:-MZw_g_l55vidlaal-BW:bt22cz5) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6b33296abd83027a861d19de94329783aa9a67d0/README.md#L356)):*
> ```
> for now
> ```
Would there be any benefit of using flux locally? How would it work?

If you don't want to answer these questions, I'll let you off by removing the "for now" :-D

**Review by lassemaatta — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/5)* status: all files reviewed, 8 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[kindcluster.sh, line 3 at r4](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-M_Jozz4-EHthVTImMZh:-M_Jozz4-EHthVTImMZi:bcrjkm9) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/09b2ab19b00334b5b540012437d230b965423635/kindcluster.sh#L3)):*
> ```
> set -eu
> ```

Perhaps this should be `set -euo pipefail` so that commands like `kustomize build "$CLUSTER_DIR" | kubectl apply -f -` will not try running `kubectl` if `kustomize` fails?
___
*[kindcluster.sh, line 72 at r4](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-M_JpZmL5UEV2vr86k_F:-M_JpZmL5UEV2vr86k_G:bvvn1zu) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/09b2ab19b00334b5b540012437d230b965423635/kindcluster.sh#L72)):*
> ```
> flux
> ```

Are we using flux when doing a local deploy?
___
*[kindcluster.sh, line 86 at r4](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-M_JqLviEi5phEatd4B-:-M_JqLviEi5phEatd4B0:bmkhj7l) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/09b2ab19b00334b5b540012437d230b965423635/kindcluster.sh#L86)):*
> ```
> jore4-local-cluster
> ```

Not necessary, but it might be a good idea (especially because they look very similar) to move these labels to the top of the file, something like

```
KUBERNETES_CONTEXT="kind-jore4-local-cluster"
KIND_CLUSTER="jore4-local-cluster"
...
```
___
*[README.md, line 357 at r4](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-M_JrfLJ2uR0q6EIxBDT:-M_JrfLJ2uR0q6EIxBDU:bsa5ef0) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/09b2ab19b00334b5b540012437d230b965423635/README.md#L357)):*
> ```
> ./kindcluster.sh setup:all --cluster=clusters/e2e
> ```

Could this be even simpler? How about something like `./kindcluster.sh start`? On the other hand, perhaps we can provide higher level utility scripts (`start_e2e.sh`, `start_local.sh`...) once we know better what the uses cases for this kind setup are..
___
*[.github/workflows/test-e2e-cluster-setup.yml, line 26 at r4](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-M_JtCiJ6686S_oN_KgZ:-M_JtCiK3enGdDqiESL0:b-u5p6i9) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/09b2ab19b00334b5b540012437d230b965423635/.github/workflows/test-e2e-cluster-setup.yml#L26)):*
> ```YAML
>             sleep 5
>             echo $i
>           done
> ```

Not strictly related to this commit, but perhaps there should be a last step where we shut down the cluster?

**Review by jschummer — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/5)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @jpeuralinna and @lassemaatta)

**Review by lassemaatta — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/5)* status: all files reviewed, 1 unresolved discussion (waiting on @jpeuralinna and @pallost)

___
*[.github/workflows/test-e2e-cluster-setup.yml, line 26 at r4](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-M_JtCiJ6686S_oN_KgZ:-Ma7WH_-DruEqD-jnliu:b-sxmd2) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/872cd44b3a64f4a29ffdc7a7b4fd431f20b77cb5/.github/workflows/test-e2e-cluster-setup.yml#L26)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

at the end of the github workflow the whole github runner is shut down / emptied, so we don't need to shut down the cluster ourselves
</blockquote></details>

I didn't mean that I'm worried some resource might keep running; rather I'd like to verify that the `stop` command actually works and doesn't e.g. throw an error.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/5)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @jpeuralinna and @lassemaatta)

___
*[.github/workflows/test-e2e-cluster-setup.yml, line 26 at r4](https://reviewable.io/reviews/hsldevcom/jore4-flux/5#-M_JtCiJ6686S_oN_KgZ:-MaCo0r5DdaOFyx0HrtJ:bs5kj09) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/872cd44b3a64f4a29ffdc7a7b4fd431f20b77cb5/.github/workflows/test-e2e-cluster-setup.yml#L26)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I didn't mean that I'm worried some resource might keep running; rather I'd like to verify that the `stop` command actually works and doesn't e.g. throw an error.
</blockquote></details>

good point, I added it!

**Review by lassemaatta — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jpeuralinna)

**Pull request merged**
