### PR TITLE
Add auth backend to Kind cluster and Azure clusters

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/18)

### CODE REVIEW

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 8 of 8 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/18)* status: all files reviewed, 2 unresolved discussions (waiting on @haphut, @jschummer, @pallost, and @tk-vincit)

___
*[clusters/e2e/jore4-local-secrets.yaml, line 32 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/18#-McsSeEN5eYcThbhcw64:-McsSeEN5eYcThbhcw65:bdf6vi9) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6acc2d331beb94c66be65f376c8c0e0bdeddbe6b/clusters/e2e/jore4-local-secrets.yaml#L32)):*
> ```YAML
>   namespace: hsl-jore4
> data:
>   oidc-client-id: "0838619941439007"
> ```

Where do these values come from? I assume these are generated in the dev-hslid for testing? Perhaps there should be a comment describing that?
___
*[clusters/test/jore4-env-patch.yaml, line 17 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/18#-McsTBKL1_cjMB9S2Iys:-McsTBKL1_cjMB9S2Iyt:b-jdicrh) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0887b4e058f86b3e95a65eedd07c5e110de43f6f/clusters/test/jore4-env-patch.yaml#L17)):*
> ```YAML
>   namespace: hsl-jore4
> data:
>   SELF_PUBLIC_BASE_URL: "https://test.jore.hsl.fi"
> ```

Not really relevant, but one has to wonder why we need 3 different env variables if they always seem to be the same value... :thinking:

**Review by tk-vincit — COMMENTED** [review]
Looks good to me, but maybe someone who is more familiar with this should approve.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/18#-:-McsVVImANSerhoL_p7q:boejiva)* status: all files reviewed, 4 unresolved discussions (waiting on @haphut, @jschummer, @lassemaatta, and @pallost)

___
*[clusters/base/jore4-services/jore4-auth.yaml, line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/18#-McsUbbK9Lv3cbr4wIhk:-McsUbbK9Lv3cbr4wIhl:bjd39fl) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0887b4e058f86b3e95a65eedd07c5e110de43f6f/clusters/base/jore4-services/jore4-auth.yaml#L9)):*
> ```YAML
> data:
>   SECRET_STORE_BASE_PATH: "/mnt/secrets-store"
>   API_PATH_PREFIX: ""
> ```

Not sure if these come from kind, but to me `API_PATH_PREFIX` and `API_PATH_PREFIX_PUBLIC` seem a little confusing - what's the difference?
___
*[clusters/test/jore4-env-patch.yaml, line 17 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/18#-McsTBKL1_cjMB9S2Iys:-McsVBKe8nhZCvMFNehK:b-j5n0g5) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0887b4e058f86b3e95a65eedd07c5e110de43f6f/clusters/test/jore4-env-patch.yaml#L17)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Not really relevant, but one has to wonder why we need 3 different env variables if they always seem to be the same value... :thinking: 
</blockquote></details>

I was wondering the same. Of course if it looks possible that we might have separate login/logout pages in the future this might be a good thing, but in the other hand if we are using hslid that doesn't seem very probable...
___
*[clusters/base/jore4-secret-bindings/jore4-secret-mappings.yaml, line 46 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/18#-McsUqFXDSBMTsMrdUUM:-McsUqFXDSBMTsMrdUUN:b-uz7pu2) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0887b4e058f86b3e95a65eedd07c5e110de43f6f/clusters/base/jore4-secret-bindings/jore4-secret-mappings.yaml#L46)):*
> ```YAML
>   parameters:
>     useVMManagedIdentity: "true"
>     tenantId: "572a41dd-c389-4f0a-b256-aefd1bf149d7"
> ```

Should we document somehow where this does come from?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/18)* status: all files reviewed, 4 unresolved discussions (waiting on @haphut, @jschummer, @lassemaatta, and @tk-vincit)

___
*[clusters/base/jore4-services/jore4-auth.yaml, line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/18#-McsUbbK9Lv3cbr4wIhk:-McxWebo1X3bZI8CH0fS:b-6urjy7) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0887b4e058f86b3e95a65eedd07c5e110de43f6f/clusters/base/jore4-services/jore4-auth.yaml#L9)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not sure if these come from kind, but to me `API_PATH_PREFIX` and `API_PATH_PREFIX_PUBLIC` seem a little confusing - what's the difference?
</blockquote></details>

this is coming from the Auth backend itself. Honestly, I don't have much better naming for this... The meanings are going to be documented in the jore4-auth repository with the next PR: https://github.com/HSLdevcom/jore4-auth/pull/6/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R88
___
*[clusters/e2e/jore4-local-secrets.yaml, line 32 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/18#-McsSeEN5eYcThbhcw64:-McxXctRB1E14V3kVDsk:bax7kej) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6acc2d331beb94c66be65f376c8c0e0bdeddbe6b/clusters/e2e/jore4-local-secrets.yaml#L32)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Where do these values come from? I assume these are generated in the dev-hslid for testing? Perhaps there should be a comment describing that?
</blockquote></details>

Added the comment
___
*[clusters/test/jore4-env-patch.yaml, line 17 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/18#-McsTBKL1_cjMB9S2Iys:-McxXgUlB0ZFB49mqztb:b8vu0uy) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0887b4e058f86b3e95a65eedd07c5e110de43f6f/clusters/test/jore4-env-patch.yaml#L17)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I was wondering the same. Of course if it looks possible that we might have separate login/logout pages in the future this might be a good thing, but in the other hand if we are using hslid that doesn't seem very probable...
</blockquote></details>

it's exactly for what @tk-vincit said: to allow redirecting to custom landing pages after logging in or logging out
___
*[clusters/base/jore4-secret-bindings/jore4-secret-mappings.yaml, line 46 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/18#-McsUqFXDSBMTsMrdUUM:-McxWGpRC4CaUJQLRuCV:b353euy) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/0887b4e058f86b3e95a65eedd07c5e110de43f6f/clusters/base/jore4-secret-bindings/jore4-secret-mappings.yaml#L46)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Should we document somehow where this does come from?
</blockquote></details>

for me it's kinda self explanatory, tenantId is the Tenant ID is from our Azure subscription. Where and in what form do you suggest me to document this...?

**Review by lassemaatta — APPROVED** [review]
I guess this is ok.

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/18#-:-McxgPg36h3uRkSgZss-:b7qf4pl)* status: all files reviewed, 2 unresolved discussions (waiting on @haphut, @jschummer, and @tk-vincit)

**Pull request merged**
