### PR TITLE
Set up test database for e2e cluster

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/12)

Closes https://github.com/HSLdevcom/jore4/issues/353

### CODE REVIEW

**Review by lassemaatta — COMMENTED** [review]
I guess this is ok, but perhaps someone else should check this out too.

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/12#-:-Mb16tM55w7tuUPE3TFc:b-x7sw19)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @jpeuralinna, @jschummer, and @pallost)

___
*[README.md, line 365 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/12#-Mb15uaC9RCRTOwqUt6r:-Mb15uaC9RCRTOwqUt6s:binadqh) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/c8aa61c69a814b6f8a3e7f0a489cfcf218b618f5/README.md#L365)):*
> ```Markdown
> - The postgresql database is exposed on `localhost:6432` (credentials are defined in
>   `clusters/e2e/jore4-local-secrets.yaml`)
> ```

I think we should do that "normalize which ports we use" thing one of these days. But that's out-of-scope for this PR.
___
*[clusters/e2e/jore4-test-database.yaml, line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/12#-Mb16X8e101MeHjfkdGo:-Mb16X8e101MeHjfkdGp:b-k4rew6) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/c8aa61c69a814b6f8a3e7f0a489cfcf218b618f5/clusters/e2e/jore4-test-database.yaml#L42)):*
> ```YAML
>       targetPort: 5432
>       # explicitly expose this port to the node
>       nodePort: 30432
> ```

Not necessary, but it might be nice to have some simple plantuml chart showing which ports are used and where. For example here it goes (if I read this correctly) 5432 -> 30432 -> 6432.

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/12)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @jpeuralinna and @lassemaatta)

___
*[README.md, line 365 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/12#-Mb15uaC9RCRTOwqUt6r:-Mb5L-1cEsO64XZmfXhY:btar3bk) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/c8aa61c69a814b6f8a3e7f0a489cfcf218b618f5/README.md#L365)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I think we should do that "normalize which ports we use" thing one of these days. But that's out-of-scope for this PR.
</blockquote></details>

The architecture wiki doc (https://github.com/HSLdevcom/jore4/blob/main/wiki/architecture.md) now contains a section about the ports used by different components in different environments. If needed, the port(s) mentioned here can be synced with that section.
___
*[clusters/e2e/jore4-test-database.yaml, line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/12#-Mb16X8e101MeHjfkdGo:-Mb5LGgH-3wOCH1caI8D:b1p6r02) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/c8aa61c69a814b6f8a3e7f0a489cfcf218b618f5/clusters/e2e/jore4-test-database.yaml#L42)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Not necessary, but it might be nice to have some simple plantuml chart showing which ports are used and where. For example here it goes (if I read this correctly) 5432 -> 30432 -> 6432.
</blockquote></details>

That document mentioned above (https://github.com/HSLdevcom/jore4/blob/main/wiki/architecture.md) could also be modified to include the port mappings.

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jpeuralinna)

**Review by lassemaatta — APPROVED** [review]
> Reviewed 6 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jpeuralinna)

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jpeuralinna)

___
*[README.md, line 365 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/12#-Mb15uaC9RCRTOwqUt6r:-MbeywwcC9tukePa-gkQ:bj2b7f0) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/c8aa61c69a814b6f8a3e7f0a489cfcf218b618f5/README.md#L365)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

The architecture wiki doc (https://github.com/HSLdevcom/jore4/blob/main/wiki/architecture.md) now contains a section about the ports used by different components in different environments. If needed, the port(s) mentioned here can be synced with that section.
</blockquote></details>

Normalized the ports and added them to the Architecture wiki page
___
*[clusters/e2e/jore4-test-database.yaml, line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/12#-Mb16X8e101MeHjfkdGo:-Mbez0tG2ZYWtFKM80ue:b-wa8m9a) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/c8aa61c69a814b6f8a3e7f0a489cfcf218b618f5/clusters/e2e/jore4-test-database.yaml#L42)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

That document mentioned above (https://github.com/HSLdevcom/jore4/blob/main/wiki/architecture.md) could also be modified to include the port mappings.
</blockquote></details>

Normalized the ports and added them to the Architecture wiki page. Also added a chart describing how the ports are mapped

**Pull request merged**
