### PR TITLE
Deploy `jore4-mbtiles-server`

### PR DESCRIPTION
**Pull request by tk-vincit**
Fixes https://github.com/HSLdevcom/jore4/issues/446

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/33)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
Otherwise looks good, but CI tests are missing

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/33#-:-Mizl0fD3M2i0nDlO1bQ:bdwyury)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

___
*[generate/values/common.yaml, line 97 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/33#-Mizkh5F5wofNjL0-92Y:-Mizkh5F5wofNjL0-92Z:bjsae1p) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/02fc7e64cca02425ab09f9d65ecfb5e3f5e5a45c/generate/values/common.yaml#L97)):*
> ```YAML
>       livenessProbe:
>         httpGet:
>           path: /services
> ```

does this server have a better endpoint for healthchecks? Something like `/health` instead of `/services`?

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/33)* status: 0 of 27 files reviewed, 2 unresolved discussions (waiting on @tk-vincit)

___
*[.github/workflows/test-e2e-cluster-setup.yml, line 151 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/33#-Mizo1U0BHyentT5ktSd:-Mizo1U1-dmSDSCa7Qm2:b-ro5plv) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9168af48239e6291a2d4f76f18a7c28093866128/.github/workflows/test-e2e-cluster-setup.yml#L151)):*
> ```YAML
>         run: |
>           MBTILES_DEPLOYED_VERSION=$(kubectl get deployment jore4-mbtiles --namespace hsl-jore4 --output jsonpath='{.spec.template.spec.containers[0].image}')
>           if [[ "${{ matrix.auth-docker-image }}" == "" ]]
> ```

this `matrix` variable is defined in the beginning of the job in the `matrix/include` yaml section. Should create these something like `mbtiles-docker-image` variable. Then also include that in the "Setup e2e cluster with the remote script" step.
And don't forget to fix this copy-pasted `matrix.auth-docker-image` everywhere to `matrix.mbtiles-docker-image` ;)

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/33)* status: 0 of 27 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[.github/workflows/test-e2e-cluster-setup.yml, line 41 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/33#-Mizp8nRD60TZcox0CRL:-Mizp8nRD60TZcox0CRM:b-elq9am) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9168af48239e6291a2d4f76f18a7c28093866128/.github/workflows/test-e2e-cluster-setup.yml#L41)):*
> ```YAML
>         with:
>           command: "curl --fail http://localhost:3300/api/auth/actuator/health --output /dev/null --silent"
> ```

the mbtiles check is missing from here

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/33)* status: 0 of 27 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[.github/workflows/test-e2e-cluster-setup.yml, line 41 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/33#-Mizp8nRD60TZcox0CRL:-MizrNQB1odqZLxivviR:boj1qgt) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9168af48239e6291a2d4f76f18a7c28093866128/.github/workflows/test-e2e-cluster-setup.yml#L41)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

the mbtiles check is missing from here
</blockquote></details>

Good catch. Done.
___
*[.github/workflows/test-e2e-cluster-setup.yml, line 151 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/33#-Mizo1U0BHyentT5ktSd:-Mizrrtb6oud-S62v3GR:b-6ylbwj) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9168af48239e6291a2d4f76f18a7c28093866128/.github/workflows/test-e2e-cluster-setup.yml#L151)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this `matrix` variable is defined in the beginning of the job in the `matrix/include` yaml section. Should create these something like `mbtiles-docker-image` variable. Then also include that in the "Setup e2e cluster with the remote script" step.
And don't forget to fix this copy-pasted `matrix.auth-docker-image` everywhere to `matrix.mbtiles-docker-image` ;)
</blockquote></details>

Done. And I think that I managed to rename auth-docker image to mbtiles-docker-image in all relevant places :sweat_smile: 
___
*[generate/values/common.yaml, line 97 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/33#-Mizkh5F5wofNjL0-92Y:-Mizpb7iCg-vKwv5W-Dj:boz1ppb) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/ee93a83d4825c97422a6495fd15da0cdcec18c32/generate/values/common.yaml#L97)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

does this server have a better endpoint for healthchecks? Something like `/health` instead of `/services`?
</blockquote></details>

Unluckily I don't think it has. :disappointed: 
https://hub.docker.com/r/deniscarriere/mbtiles-server

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/33)* status: 0 of 27 files reviewed, all discussions resolved (waiting on @tk-vincit)

**Pull request merged**
