### PR TITLE
Generating docker-compose e2e setup with gomplate

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/27)

Closes https://github.com/HSLdevcom/jore4/issues/410

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
Nice work! Minor things to consider...

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-:-MiuUTL2CUoXRfmosouL:bppwlu)* status: 0 of 30 files reviewed, 7 unresolved discussions (waiting on @jarkkoka, @jpeuralinna, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[README.md, line 467 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-MitdAQAC7C-Zcl1qxgt:-MitdAQAC7C-Zcl1qxgu:bwapmgh) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/README.md#L467)):*
> ```Markdown
> [docker-compose](https://docs.docker.com/compose/). Whenever the `clusters/docker-compose` directory is updated in the `e2e` branch, a new version of the release tar.gz is created in the [repository](https://github.com/HSLdevcom/jore4-flux/releases).
> 
> You may use the following script for downloading and starting up docker-compose in your repository.
> ```

This is somehow confusing. If this is supposed to be a script, why it is in readme and not in a separate file? Or if this is supposed to be just an example of ~two command line commands, why it tries to be a "script" in the first place?
___
*[README.md, line 488 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-Mitd5ZxE__b5OjZjvPN:-Mitd5ZxE__b5OjZjvPO:bltg4s8) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/README.md#L488)):*
> ```Markdown
> ```
> 
> As there is a new version coming of this docker-compose package, it's wise to add the `./docker`
> ```

Is there a reason why it is not in gitignore already? 
___
*[.github/workflows/release-docker-compose.yml, line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-Mitjv6G3jcNYm-RgUCz:-Mitjv6G3jcNYm-RgUD-:bk9ckf) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/.github/workflows/release-docker-compose.yml#L17)):*
> ```YAML
>         uses: actions/checkout@v2
> 
>       # Left this here in case we need to use git tag for naming the github release
> ```

Not sure if leaving this here makes actually sense. This seems to be relatively simple thing to do, so why break the "never commit commented out code" rule. But as you wish.
___
*[.github/workflows/release-docker-compose.yml, line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-Mitkjy3DJ_9FiMM3l3b:-Mitkjy3DJ_9FiMM3l3c:b8y13qm) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/.github/workflows/release-docker-compose.yml#L24)):*
> ```YAML
>         env:
>           RELEASE_VERSION: e2e-docker-compose
>         # 1. create a tar.gz of the docker-compose config + dependencies
> ```

I would put these as close to corresponding commands as possible. Now these get very easily outdated if something changes.
___
*[.github/workflows/release-docker-compose.yml, line 29 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-MitkQWo-GNNAML4e4Vx:-MitkQWo-GNNAML4e4Vy:b7hhfzb) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/.github/workflows/release-docker-compose.yml#L29)):*
> ```YAML
>         run: |
>           echo "Release version: ${RELEASE_VERSION}"
>           echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
> ```

Does this print GITHUB_TOKEN to logs or pipe it to the next command?  I guess we don't want to log this. Could you just do something like `gh auth login --with-token "${{ secrets.GITHUB_TOKEN }}"`? 
___
*[clusters/docker-compose/docker-compose.yml, line 94 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-MiuRU0kAcEszVFpBMcK:-MiuRU0kAcEszVFpBMcL:b-k5aor) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/clusters/docker-compose/docker-compose.yml#L94)):*
> ```YAML
>       - "127.0.0.1:3302:80"
> 
>   proxy:
> ```

All other containers seems to be named as `jore4-something`, so should this rather be `jore4-proxy`?
___
*[clusters/docker-compose/secret-auth-oidc-client-secret, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-MiuQtJx0L2S0qav-HaI:-MiuQtJx0L2S0qav-HaJ:b-86od98) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/clusters/docker-compose/secret-auth-oidc-client-secret#L1)):*
> ```
> 9uV5p45F6IZQubCErBiquZYaL7Wm2AWM
> ```

Why passwords sometimes look like "real" passwords (like this one) and sometimes are more placeholders (e.g. "postgres")?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/27)* status: 0 of 30 files reviewed, 7 unresolved discussions (waiting on @jarkkoka, @jpeuralinna, @jschummer, @pkainulainen-vincit, and @tk-vincit)

___
*[README.md, line 467 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-MitdAQAC7C-Zcl1qxgt:-MiuaVOU3Khcc2Wz6ymZ:b-uc7ewx) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/README.md#L467)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This is somehow confusing. If this is supposed to be a script, why it is in readme and not in a separate file? Or if this is supposed to be just an example of ~two command line commands, why it tries to be a "script" in the first place?
</blockquote></details>

I extended the README to clarify what's the purpose of this script. (To be run on your own project workspace and put your customizations that are necessary to run it in your own context) Is it okay now?
___
*[README.md, line 488 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-Mitd5ZxE__b5OjZjvPN:-MiuaMw3AQd9pI1Av37Z:b-5x7ehl) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/README.md#L488)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Is there a reason why it is not in gitignore already? 
</blockquote></details>

The .gitignore of the repository that is using this docker-compose package, not _this_ repository
___
*[.github/workflows/release-docker-compose.yml, line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-Mitjv6G3jcNYm-RgUCz:-MiuaD2y7xlGPxVO8LPH:bb2xju2) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/.github/workflows/release-docker-compose.yml#L17)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not sure if leaving this here makes actually sense. This seems to be relatively simple thing to do, so why break the "never commit commented out code" rule. But as you wish.
</blockquote></details>

And apparently this code doesn't work either in every occasion... I guess when we'll need it, we'll just create a stable version in `jore4-tools` repo. For now, I'll remove this comment
___
*[.github/workflows/release-docker-compose.yml, line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-Mitkjy3DJ_9FiMM3l3b:-Miua6bP6-nOjrFOibXH:b-t2ob4r) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/.github/workflows/release-docker-compose.yml#L24)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I would put these as close to corresponding commands as possible. Now these get very easily outdated if something changes.
</blockquote></details>

I was under the impression that I can't have comments in the `run |` section. I was wrong... I moved the comments there!
___
*[.github/workflows/release-docker-compose.yml, line 29 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-MitkQWo-GNNAML4e4Vx:-Miu_tqu4PUFR0QCgLBg:b-s326y3) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/.github/workflows/release-docker-compose.yml#L29)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Does this print GITHUB_TOKEN to logs or pipe it to the next command?  I guess we don't want to log this. Could you just do something like `gh auth login --with-token "${{ secrets.GITHUB_TOKEN }}"`? 
</blockquote></details>

gh auth login actually opens an interactive shell, so you can't set the secret as a parameter. On the other hand if you pipe the echo command, it does not actually get written to the stdout. See e.g. https://github.com/HSLdevcom/jore4-flux/runs/3523481717?check_suite_focus=true
___
*[clusters/docker-compose/docker-compose.yml, line 94 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-MiuRU0kAcEszVFpBMcK:-MiubEEv-_zK4APXvOcD:bb7f2mf) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/clusters/docker-compose/docker-compose.yml#L94)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

All other containers seems to be named as `jore4-something`, so should this rather be `jore4-proxy`?
</blockquote></details>

done
___
*[clusters/docker-compose/secret-auth-oidc-client-secret, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-MiuQtJx0L2S0qav-HaI:-MiubGO415NWD-A0LSWw:bmiuit) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/clusters/docker-compose/secret-auth-oidc-client-secret#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why passwords sometimes look like "real" passwords (like this one) and sometimes are more placeholders (e.g. "postgres")?
</blockquote></details>

because this is a real password :) this is what we use to access the actual HSL ID environment. All other secrets are just used locally

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/27)* status: 0 of 30 files reviewed, 3 unresolved discussions (waiting on @jarkkoka, @jpeuralinna, @jschummer, @pallost, @pkainulainen-vincit, and @tk-vincit)

___
*[README.md, line 467 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-MitdAQAC7C-Zcl1qxgt:-MiugtjiBdUuCX7mgXvQ:b-2zxr1j) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/README.md#L467)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I extended the README to clarify what's the purpose of this script. (To be run on your own project workspace and put your customizations that are necessary to run it in your own context) Is it okay now?
</blockquote></details>

At least it is better now. :+1: 

Just wondering: why would one have to run this script in another project's workspace, why not just run it from here?
___
*[.github/workflows/release-docker-compose.yml, line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-Mitkjy3DJ_9FiMM3l3b:-MiudZBL1cuq7DT447wb:b-ucfknh) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/.github/workflows/release-docker-compose.yml#L24)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I was under the impression that I can't have comments in the `run |` section. I was wrong... I moved the comments there!
</blockquote></details>

Thanks!
___
*[.github/workflows/release-docker-compose.yml, line 29 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-MitkQWo-GNNAML4e4Vx:-Miuda4j8jpRfx7ZhBwr:bb71kmx) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/.github/workflows/release-docker-compose.yml#L29)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

gh auth login actually opens an interactive shell, so you can't set the secret as a parameter. On the other hand if you pipe the echo command, it does not actually get written to the stdout. See e.g. https://github.com/HSLdevcom/jore4-flux/runs/3523481717?check_suite_focus=true
</blockquote></details>

Okay

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/27)* status: 0 of 30 files reviewed, 3 unresolved discussions (waiting on @jarkkoka, @jpeuralinna, @jschummer, @pkainulainen-vincit, and @tk-vincit)

___
*[README.md, line 467 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-MitdAQAC7C-Zcl1qxgt:-MiulWqC0Gx3eROE9u2M:bswau7l) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/README.md#L467)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

At least it is better now. :+1: 

Just wondering: why would one have to run this script in another project's workspace, why not just run it from here?
</blockquote></details>

Well, every project needs a different kind of customization to this docker-compose. Every project wants to substitute a different service from this docker-compose with the service running on the host.

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/27)* status: 0 of 30 files reviewed, 2 unresolved discussions (waiting on @jarkkoka, @jpeuralinna, @jschummer, @pkainulainen-vincit, and @tk-vincit)

___
*[README.md, line 467 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/27#-MitdAQAC7C-Zcl1qxgt:-Mium-jREXgElFQkqb3I:b-8fx2u7) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/6e74c7a28cea8c05795a0367e2efff1f637d2701/README.md#L467)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Well, every project needs a different kind of customization to this docker-compose. Every project wants to substitute a different service from this docker-compose with the service running on the host.
</blockquote></details>

:+1:

**Pull request merged**
