### PR TITLE
Upgrade Flux to 0.13.2

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/7)

### CODE REVIEW

**Review by lassemaatta — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/7)* status: all files reviewed, 1 unresolved discussion (waiting on @jschummer, @pallost, and @tk-vincit)

___
*[crd/flux-crd.yaml, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/7#-MZqg8-O0lWU1wCUlapY:-MZqg8-O0lWU1wCUlapZ:b-v578w5) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/c9674acf10f25566c3827f25a8a073ade26500d9/crd/flux-crd.yaml#L5)):*
> ```YAML
> # Components: source-controller,kustomize-controller,helm-controller,notification-controller
> # Generated file, see README.md how to obtain/update it
> apiVersion: v1
> ```

I knew this line was going to disappear :)

**Review by jschummer — CHANGES_REQUESTED** [review]
Maybe you could add a line like "Also added shortnames to ..." or "Also other minor improvements included ..." to the commit message? (If I got it right, the shortnames may be the only minor improvements?)

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/7#-:-MZwRPPjDPFKNZhlLFqS:by9nwdq)* status: all files reviewed, 2 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[crd/flux-crd.yaml, line 1156 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/7#-MZwQmmYDwl26lUXQDv2:-MZwQmmYDwl26lUXQDv3:bftv50y) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/1be224b66b67b8fbef11a76346a84cbd70609f5b/crd/flux-crd.yaml#L1156)):*
> ```
> CRDs 
> ```
Is the first "CRDs" meant to be there? Now it says "CDRs upgrade CRDs" :grimacing:

**Review by pallost — COMMENTED** [review]
I don't know what actually got updated, I just try to keep the versions up to date... I added a link to the commit message where to find the changelog from if someone wants to look up what changed

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/7#-:-M_-aEaGCzlIJNfmDVoU:b-gftekk)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jschummer, @lassemaatta, and @tk-vincit)

___
*[crd/flux-crd.yaml, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/7#-MZqg8-O0lWU1wCUlapY:-M_-_aFOEVj6pfFq8Ray:b-lpyyxm) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/c9674acf10f25566c3827f25a8a073ade26500d9/crd/flux-crd.yaml#L5)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I knew this line was going to disappear :)
</blockquote></details>

And you were absolutely right :D 
___
*[crd/flux-crd.yaml, line 1156 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/7#-MZwQmmYDwl26lUXQDv2:-M_-_VmD1P1qPrshCVHD:b73ztl2) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/1be224b66b67b8fbef11a76346a84cbd70609f5b/crd/flux-crd.yaml#L1156)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> CRDs 
> ```
Is the first "CRDs" meant to be there? Now it says "CDRs upgrade CRDs" :grimacing: 
</blockquote></details>

This is a generated file, I don't control its contents. Or actually I could but it'll be overwritten anyway... :) But yes, CRDs are in fact upgrading other CRDs here, it's intentional.

**Review by lassemaatta — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/7)* status: all files reviewed, 1 unresolved discussion (waiting on @jschummer and @tk-vincit)

**Pull request merged**
