### PR TITLE
Update e2e testdb to have dedicated databases for auth and jore3importer

### PR DESCRIPTION
**Pull request by pallost**
Also set auth and jore3importer to use the new databases instead of jore4

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/44)

### CODE REVIEW

**Review by jschummer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/44)* status: 0 of 25 files reviewed, 3 unresolved discussions (waiting on @jschummer and @pallost)

___
*[generate/values/common.yaml, line 31 at r4](https://reviewable.io/reviews/hsldevcom/jore4-flux/44#-MnVLfOoBFDGhuENH0bv:-MnVLfOoBFDGhuENH0bw:bl471eg) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/2c84258005ed0fe8e4e7a9db76256d43615d26d4/generate/values/common.yaml#L31)):*
> ```
> public
> ```
In theory the whole schema handling could have been removed from the auth backend, but maybe it's actually not a bad thing to have this here verbosely. And probably it is less work this way, so :+1: 
___
*[generate/values/e2e.yaml, line 64 at r4](https://reviewable.io/reviews/hsldevcom/jore4-flux/44#-MnVL99jAZJYMD_NbTQ6:-MnVL99jAZJYMD_NbTQ7:b8kzsny) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/2c84258005ed0fe8e4e7a9db76256d43615d26d4/generate/values/e2e.yaml#L64)):*
> ```
> create-logical-databases--451112984066a8d2f702ac0e719e3127ae8ac2e6"
> ```
Should we wait with integrating this into the main branch until the docker images can point to main branch tags also?
___
*[generate/values/e2e.yaml, line 87 at r4](https://reviewable.io/reviews/hsldevcom/jore4-flux/44#-MnVLcOR8DVnQyaZ7Nnq:-MnVLcOR8DVnQyaZ7Nnr:bm4hm63) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/2c84258005ed0fe8e4e7a9db76256d43615d26d4/generate/values/e2e.yaml#L87)):*
> ```
> fix-healthcheck--8a78d9bead1db0fd7932c089df7d65a8cf9f18e6"
> ```
See above

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/44)* status: 0 of 25 files reviewed, 3 unresolved discussions (waiting on @jschummer)

___
*[generate/values/common.yaml, line 31 at r4](https://reviewable.io/reviews/hsldevcom/jore4-flux/44#-MnVLfOoBFDGhuENH0bv:-MnVUQwB0S2n-yc0Jlt1:bwlm5ic) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/2c84258005ed0fe8e4e7a9db76256d43615d26d4/generate/values/common.yaml#L31)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> public
> ```
In theory the whole schema handling could have been removed from the auth backend, but maybe it's actually not a bad thing to have this here verbosely. And probably it is less work this way, so :+1: 
</blockquote></details>

well, it was not in the scope of this PR... but to make auth backend work with the new database, I has to change the schema to 'public'
___
*[generate/values/e2e.yaml, line 64 at r4](https://reviewable.io/reviews/hsldevcom/jore4-flux/44#-MnVL99jAZJYMD_NbTQ6:-MnVVLO1Ai7upEArjTsY:b2od65j) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/2c84258005ed0fe8e4e7a9db76256d43615d26d4/generate/values/e2e.yaml#L64)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> create-logical-databases--451112984066a8d2f702ac0e719e3127ae8ac2e6"
> ```
Should we wait with integrating this into the main branch until the docker images can point to main branch tags also?
</blockquote></details>

ok, now the version is updated to 'main'
___
*[generate/values/e2e.yaml, line 87 at r4](https://reviewable.io/reviews/hsldevcom/jore4-flux/44#-MnVLcOR8DVnQyaZ7Nnq:-MnVVP83Cls0UnwZN3xy:b-20pq4e) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/2c84258005ed0fe8e4e7a9db76256d43615d26d4/generate/values/e2e.yaml#L87)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> fix-healthcheck--8a78d9bead1db0fd7932c089df7d65a8cf9f18e6"
> ```
See above
</blockquote></details>

updated to 'main'

**Review by pkainulainen-vincit — APPROVED** [review]
This PR looks good to me, but I think that's good idea to have someone else to check this PR as well.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/44#-:-Mnz618nA7cdr8ckt78g:b63pla1)* status: 0 of 33 files reviewed, 3 unresolved discussions (waiting on @jschummer)

**Review by jschummer — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/44#-:-MnzOAnp63rYuZxyl8UC:bnfp4nl)* status: 0 of 33 files reviewed, 3 unresolved discussions (waiting on @jschummer)

**Pull request merged**
