### PR TITLE
Deployment strategy

### PR DESCRIPTION
**Pull request by pallost**
Builds on top of https://github.com/HSLdevcom/jore4-flux/pull/2
Closes https://github.com/HSLdevcom/jore4/issues/190

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/3)

### CODE REVIEW

**Review by lassemaatta — CHANGES_REQUESTED** [review]
> Reviewed 39 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/3)* status: all files reviewed, 12 unresolved discussions (waiting on @haphut, @jschummer, and @pallost)

___
*[kubernetes.sh, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYizNgOEP2mYejQvShr:-MYizNgOEP2mYejQvShs:bgrbcq7) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/kubernetes.sh#L16)):*
> ```Shell
> function check_context {
>   echo "Checking whether $1 context is active"
> ```

What happens if the user (accidentally) provides the wrong stage? e.g. `kubernetes.sh deploy:cluster testing`? We probably get some error message, but should we explicitly check that the `stage` is a valid value?

Something like

```bash
STAGES=("dev" "test" "prod")
TARGET_STAGE="$2"

if [[ ! " ${STAGES[*]} " =~ $TARGET_STAGE ]]
then
  echo "Unexpected stage, expected one of (dev, test, prod)"
  exit 1
fi
```

(also, should we switch to babashka? I hate bash syntax.. :trollface: )
___
*[README.md, line 114 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj0VjM16HoX8zt37yd:-MYj0VjN6gYgyJbtpeC6:b-lxp8sl) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/README.md#L114)):*
> ```Markdown
> _Rule 1:_ We should be able to pinpoint with a high confidence that at what _time_ in what _stage_ what
> _version_ was deployed. We are aiming to use the git history for this, which is of course not 100%
> reliable, because failed deployments don't show in the git history. We are assuming here that git
> ```

Perhaps also mention that there is naturally some delay between creating the merge commit locally and pushing it to github (assuming we're not using some script to do it).
___
*[README.md, line 169 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj1EBR-5rIgWlJn4Rq:-MYj1EBR-5rIgWlJn4Rr:b-8tevy9) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/README.md#L169)):*
> ```
> git history that for a while a faulty configuration was deployed. Instead, always create a new commit
> to the `main` branch that reverts the changes back to the desired state and propagate it the usual way
> ```

This works, but depending on the state of the branches it might take a while before the fix is propagated. For example, we update `test` based on a version that was running on `dev` last week but notice that it doesn't work at all even though `dev` was fine. We detect the issue and fix the problem with a new commit in `main`. However, what if there are dozens of other commits (which might contain features we don't yet want in `test`) in `main` that haven't even been in `dev` yet? Or maybe they are in `dev`, but the actual `dev` commit we originally wanted to merge into `test` did not contain them (because we might update `dev` much more frequently than `test`) ? 

I don't really have a "silver-bullet" solution to this; the best I can think of is to try to avoid bringing major changes to `main` if we're in the middle of a "we're going to update production as soon as the test environment is up-to-date and stable"- situation.
___
*[README.md, line 172 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj4Bsz8BYjx9X6cVTB:-MYj4Bsz8BYjx9X6cVTC:b99arxi) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/README.md#L172)):*
> ```
> In case you want to do a hotfix in production for a critical issue, you may create the hotfix in
> `main` and propagate if to `prod` with the `--no-ff` merge. On in some cases you may want to create a
> ```

I'm not sure if this is a good idea, because this may bring additional commits from `main` to `prod`, completely short-circuiting the `dev` and `test` branches. I'd rather create a separate commit directly in the `prod` branch and perhaps mark it with a tag for documentation, and also naturally fix it in `main`. Then later when the fix slowly propagates from `main`->`dev`->`test` all the way back to `prod`, we can do a `no-ff` merge on the original `prod` branch _before_ the hotfix was implemented, and move the `origin/prod` branch from the hotfix commit to the newly created merge commit. The original hotfix commit will remain tagged but won't appear in the `prod` branch anymore (which is unfortunate).

Alternatively, we might keep the hotfix in the `prod` branch, but then there's the risk that you encounter a merge conflict some day when merging stuff from `test`->`prod`.
___
*[README.md, line 276 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj6UTL-5gFTDxSbMZn:-MYj6UTL-5gFTDxSbMZo:bsefz0v) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/README.md#L276)):*
> ```
> `kustomize build ...`
> ```

Maybe add a literal example of this?
___
*[README.md, line 281 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj6_UWEL8P9qqdN49b:-MYj6_UWEL8P9qqdN49c:b-tb9zyz) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/README.md#L281)):*
> ```
> If you
> ```

There might be something missing here..
___
*[README.md, line 283 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj6omE5UNibpPoMcSg:-MYj6omE5UNibpPoMcSh:b-hi7o2o) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/README.md#L283)):*
> ```
> it's
> ```

its
___
*[.github/linters/.ecrc, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj6w921cf1LKaTnI5a:-MYj6w921cf1LKaTnI5b:bwtb6fb) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/.github/linters/.ecrc#L7)):*
> ```
> exclude
> ```

Why isn't this in upper case like the others? :mild-panic:
___
*[.github/workflows/doctoc.yml, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj7bJI-Lunm8ymkMRM:-MYj7bJI-Lunm8ymkMRN:byp10io) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/.github/workflows/doctoc.yml#L11)):*
> ```
> latest
> ```

Should we use a specific version? Same comment applies to the other actions as well.
___
*[.github/workflows/test-kustomize.yml, line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj7iuzAQ0SqtEtdlv5:-MYj7iuzAQ0SqtEtdlv6:b-kntvvp) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/.github/workflows/test-kustomize.yml#L19)):*
> ```
> master
> ```

Should we use a specific tag/hash here (also below)?
___
*[clusters/dev/jore4-env-patch.yaml, line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj8GJ4A1_3Xcxmdmxm:-MYj8GJ4A1_3Xcxmdmxn:bzf9931) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/clusters/dev/jore4-env-patch.yaml#L15)):*
> ```YAML
>           env:
>             - name: LOG_LEVEL
>               value: "warning"
> ```

I assume this is just some sort of an example?
___
*[crd/flux-crd.yaml, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj8s3I3VCkPv9qb1Cj:-MYj8s3I3VCkPv9qb1Ck:b-snyfom) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/crd/flux-crd.yaml#L2)):*
> ```YAML
> ---
> # Flux version: v0.12.3
> ```

I assume this file was fetched from somewhere or generated by some tool? Perhaps add some comment describing where this was obtained.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/3)* status: 30 of 39 files reviewed, 12 unresolved discussions (waiting on @haphut, @jschummer, and @lassemaatta)

___
*[kubernetes.sh, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYizNgOEP2mYejQvShr:-MYxfKHH37euB0VfKY5y:bs6a68n) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/kubernetes.sh#L16)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

What happens if the user (accidentally) provides the wrong stage? e.g. `kubernetes.sh deploy:cluster testing`? We probably get some error message, but should we explicitly check that the `stage` is a valid value?

Something like

```bash
STAGES=("dev" "test" "prod")
TARGET_STAGE="$2"

if [[ ! " ${STAGES[*]} " =~ $TARGET_STAGE ]]
then
  echo "Unexpected stage, expected one of (dev, test, prod)"
  exit 1
fi
```

(also, should we switch to babashka? I hate bash syntax.. :trollface: )
</blockquote></details>

I'd love to try babashka, but only if we can find a solution that the runtime installs automatically when someone executes a script like this :)

User's cannot log in to clusters that don't exist, so if you try to call `kubernetes.sh deploy:cluster testing`, it'll just say `Resource group 'hsl-jore4-testing' could not be found.` Is that enough of do you wish that I put an additional check to the script as you suggested?
___
*[README.md, line 114 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj0VjM16HoX8zt37yd:-MYxgmA7BT4PWlkwUpXB:b-3vqws1) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/README.md#L114)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Perhaps also mention that there is naturally some delay between creating the merge commit locally and pushing it to github (assuming we're not using some script to do it).
</blockquote></details>

OK, extended the README
___
*[README.md, line 169 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj1EBR-5rIgWlJn4Rq:-MYxgwLA75dOrQ2KrliL:b-ohdmzm) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/README.md#L169)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> git history that for a while a faulty configuration was deployed. Instead, always create a new commit
> to the `main` branch that reverts the changes back to the desired state and propagate it the usual way
> ```

This works, but depending on the state of the branches it might take a while before the fix is propagated. For example, we update `test` based on a version that was running on `dev` last week but notice that it doesn't work at all even though `dev` was fine. We detect the issue and fix the problem with a new commit in `main`. However, what if there are dozens of other commits (which might contain features we don't yet want in `test`) in `main` that haven't even been in `dev` yet? Or maybe they are in `dev`, but the actual `dev` commit we originally wanted to merge into `test` did not contain them (because we might update `dev` much more frequently than `test`) ? 

I don't really have a "silver-bullet" solution to this; the best I can think of is to try to avoid bringing major changes to `main` if we're in the middle of a "we're going to update production as soon as the test environment is up-to-date and stable"- situation.
</blockquote></details>

I don't really know what would be a good solution for this... but most likely would approach the problem with `git rebase` :) I think we'll handle these issues one by one, there's no generally good solution...
___
*[README.md, line 172 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj4Bsz8BYjx9X6cVTB:-MYxhwLt6TzwnaS-2Clb:b-l2l332) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/README.md#L172)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> In case you want to do a hotfix in production for a critical issue, you may create the hotfix in
> `main` and propagate if to `prod` with the `--no-ff` merge. On in some cases you may want to create a
> ```

I'm not sure if this is a good idea, because this may bring additional commits from `main` to `prod`, completely short-circuiting the `dev` and `test` branches. I'd rather create a separate commit directly in the `prod` branch and perhaps mark it with a tag for documentation, and also naturally fix it in `main`. Then later when the fix slowly propagates from `main`->`dev`->`test` all the way back to `prod`, we can do a `no-ff` merge on the original `prod` branch _before_ the hotfix was implemented, and move the `origin/prod` branch from the hotfix commit to the newly created merge commit. The original hotfix commit will remain tagged but won't appear in the `prod` branch anymore (which is unfortunate).

Alternatively, we might keep the hotfix in the `prod` branch, but then there's the risk that you encounter a merge conflict some day when merging stuff from `test`->`prod`.
</blockquote></details>

true... as mentioned in your previous comment, at this point `main` might have already have some additional commits that we don't want to bring to the `prod` hotfix. I'll suggest placing the hotfix to `prod` directly and then cherry-pick it to `main` as well
___
*[README.md, line 276 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj6UTL-5gFTDxSbMZn:-MYxj2Mr1T6YcVJDuHSn:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/README.md#L276)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> `kustomize build ...`
> ```

Maybe add a literal example of this?
</blockquote></details>

Done.
___
*[README.md, line 281 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj6_UWEL8P9qqdN49b:-MYxjBkfElKwXDSZI-Zy:ba3dfob) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/README.md#L281)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> If you
> ```

There might be something missing here..
</blockquote></details>

Removed
___
*[README.md, line 283 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj6omE5UNibpPoMcSg:-MYxjFMW2JB_lj6uP1Zc:b-7ql1td) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/README.md#L283)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> it's
> ```

its

</blockquote></details>

fixed
___
*[.github/linters/.ecrc, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj6w921cf1LKaTnI5a:-MYxjhGP-Oi_6Y1bSIOn:benopsw) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/.github/linters/.ecrc#L7)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> exclude
> ```

Why isn't this in upper case like the others? :mild-panic:
</blockquote></details>

Funnily, it seems to be completely inconsistent:

https://github.com/editorconfig-checker/editorconfig-checker#manually-excluding uses lowercase
https://github.com/editorconfig-checker/editorconfig-checker#configuration uses uppercase
https://github.com/editorconfig-checker/editorconfig-checker/blob/master/.ecrc uses randomcase :P

for consistency, I made them all uppercase
___
*[.github/workflows/doctoc.yml, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj7bJI-Lunm8ymkMRM:-MYxkIkH9y1uyq3VM6W5:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/.github/workflows/doctoc.yml#L11)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> latest
> ```

Should we use a specific version? Same comment applies to the other actions as well.
</blockquote></details>

Done.
___
*[.github/workflows/test-kustomize.yml, line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj7iuzAQ0SqtEtdlv5:-MYxkQ1Z05apDhbeBB2-:bk59sd5) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/.github/workflows/test-kustomize.yml#L19)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> master
> ```

Should we use a specific tag/hash here (also below)?
</blockquote></details>

uhh, well, why not...
___
*[clusters/dev/jore4-env-patch.yaml, line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj8GJ4A1_3Xcxmdmxm:-MYxlFRx6WiOxE2j3cw2:bs8evpr) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/clusters/dev/jore4-env-patch.yaml#L15)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I assume this is just some sort of an example?
</blockquote></details>

jepp, I'll rename it to make it obvious :)
___
*[crd/flux-crd.yaml, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj8s3I3VCkPv9qb1Cj:-MYxlJogCFbNUqT0QaXN:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/crd/flux-crd.yaml#L2)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I assume this file was fetched from somewhere or generated by some tool? Perhaps add some comment describing where this was obtained.
</blockquote></details>

OK

**Review by lassemaatta — APPROVED** [review]
Looks ok to me, but perhaps someone else should look at this too.

> Reviewed 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-:-MYxsc49EgVgU2ZPkZig:bgcl14)* status: 38 of 39 files reviewed, all discussions resolved (waiting on @haphut, @jschummer, and @lassemaatta)

___
*[kubernetes.sh, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYizNgOEP2mYejQvShr:-MYxs7y399_Afm9chjVA:b-cvte6u) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/kubernetes.sh#L16)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd love to try babashka, but only if we can find a solution that the runtime installs automatically when someone executes a script like this :)

User's cannot log in to clusters that don't exist, so if you try to call `kubernetes.sh deploy:cluster testing`, it'll just say `Resource group 'hsl-jore4-testing' could not be found.` Is that enough of do you wish that I put an additional check to the script as you suggested?
</blockquote></details>

I guess that's ok.
___
*[.github/workflows/test-kustomize.yml, line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj7iuzAQ0SqtEtdlv5:-MYxpQjx3jG02N1wb-FW:bjz1huf) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/.github/workflows/test-kustomize.yml#L19)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

uhh, well, why not...
</blockquote></details>

I'm mostly just worried about a) stability in the CI build even if the library author (`karancode`) commits some backwards incompatible changes to `master` or b) security if someone manages to get malicious code into the library.
___
*[crd/flux-crd.yaml, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj8s3I3VCkPv9qb1Cj:-MYxrRR1EppfvLJu9_B1:bafrj0b) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/crd/flux-crd.yaml#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

OK
</blockquote></details>

If this is a generated file, then I assume that the comment should perhaps be somewhere else (but nearby)? Otherwise the next time it's generated it's unlikely that the person will remember adding the comment again. (I sometimes put a `README.md` in the same directory to describe its contents). 

But this is not a big deal.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/3)* status: 38 of 39 files reviewed, all discussions resolved (waiting on @haphut, @jschummer, and @lassemaatta)

___
*[crd/flux-crd.yaml, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYj8s3I3VCkPv9qb1Cj:-MYy5Obu5UYQLFEFDIGF:bh3rlf1) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/9cb157a2e2d01fe8474ec8908b28f01122f88dea/crd/flux-crd.yaml#L2)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

If this is a generated file, then I assume that the comment should perhaps be somewhere else (but nearby)? Otherwise the next time it's generated it's unlikely that the person will remember adding the comment again. (I sometimes put a `README.md` in the same directory to describe its contents). 

But this is not a big deal.
</blockquote></details>

Well, this IS decribed in the README.md already :)

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/3)* status: 38 of 39 files reviewed, all discussions resolved (waiting on @haphut, @jschummer, and @lassemaatta)

___
*[README.md, line 118 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYy_7L44YjTTyCdNEiE:-MYy_7L44YjTTyCdNEiF:bmfsip6) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/1ffc1813212f21513fb9613357328b93a5302c00/README.md#L118)):*
> ```Markdown
> - failed deployments don't show in the git history
> - deployments only happen if the commit is actually pushed to github
> - deployments take some time
> ```

- users can rewrite git history with force push :wink:

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/3)* status: 38 of 39 files reviewed, 1 unresolved discussion (waiting on @haphut, @jschummer, @lassemaatta, and @pallost)

___
*[clusters/base/jore4-services/jore4-frontend.yaml, line 6 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MZBrge50D_luACkzkzk:-MZBrge50D_luACkzkzl:b-cw38nj) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/1ffc1813212f21513fb9613357328b93a5302c00/clusters/base/jore4-services/jore4-frontend.yaml#L6)):*
> ```YAML
> kind: Deployment
> metadata:
>   name: jore4-frontend
> ```

`jore4-frontend` or `jore4-ui`? Latter one is name of git repository and docker image.

**Review by lassemaatta — APPROVED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/3)* status: all files reviewed, 1 unresolved discussion (waiting on @haphut, @jschummer, and @pallost)

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/3)* status: all files reviewed, 1 unresolved discussion (waiting on @haphut, @jschummer, and @tk-vincit)

___
*[README.md, line 118 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MYy_7L44YjTTyCdNEiE:-MZCd5fDAYYWIfay-6jP:bniecxl) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/1ffc1813212f21513fb9613357328b93a5302c00/README.md#L118)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

- users can rewrite git history with force push :wink: 
</blockquote></details>

I'll add that, but I think we can find 10+ more reasons where this could fail :D That's why I added the following sentence: "We are assuming here that git commits contain configurations which will succeed to deploy and the
time delay is negligible." ;)
___
*[clusters/base/jore4-services/jore4-frontend.yaml, line 6 at r2](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MZBrge50D_luACkzkzk:-MZCdbKq960-Eb6yer_i:b9kz0kz) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/1ffc1813212f21513fb9613357328b93a5302c00/clusters/base/jore4-services/jore4-frontend.yaml#L6)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`jore4-frontend` or `jore4-ui`? Latter one is name of git repository and docker image. 
</blockquote></details>

I'll rename everything once we finally have some stable modules and a clear vision what are the pieces of the puzzle... jore4-backend is also badly named but that's all what we have for now :)

**Review by lassemaatta — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haphut and @jschummer)

**Review by jschummer — APPROVED** [review]
As discussed elsewhere, :lgtm: but some minor things could be improved in the readme.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-:-MZM4jb28fmHYkl2s8VW:bq3t87f)* status: all files reviewed, 4 unresolved discussions (waiting on @haphut and @pallost)

___
*[README.md, line 112 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MZIiVry2OWsNr8oKoIt:-MZIiVry2OWsNr8oKoIu:b-m3kb92) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/e8da9995c611a56679f1609c60f40012cce65ee9/README.md#L112)):*
> ```
>  with a high confidence that at what
> ```
I think the "that at what" is maybe not so good English, also the "a" in "a high confidence" should probably go.

Would maybe something like "We should be able to pinpoint the time, stage, and version of what was deployed" work?

The "high confidence" can of course also be put back in there :-)
___
*[README.md, line 132 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MZIiiP1Cvyrnd-g8pq0:-MZIiiP1Cvyrnd-g8pq1:b-y20juz) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/e8da9995c611a56679f1609c60f40012cce65ee9/README.md#L132)):*
> ```
> do
> ```
"do" in the end not needed / artifact from previous version?
___
*[README.md, line 139 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MZIipgz0kgED18wznJk:-MZIipgz0kgED18wznJl:b84kicl) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/e8da9995c611a56679f1609c60f40012cce65ee9/README.md#L139)):*
> ```
> no fast-forward
> ```
For clarity, maybe better to use an additional dash: "no-fast-forward"
___
*[README.md, line 140 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MZIiw8y18z4_n5Nds4Q:-MZIiw8y18z4_n5Nds4R:b2svgyu) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/e8da9995c611a56679f1609c60f40012cce65ee9/README.md#L140)):*
> ```
> testity of
> ```
Did you mean "testify" instead of "testity of"?
___
*[README.md, line 168 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MZIj0qM3yL9376t--TX:-MZIj0qM3yL9376t--TY:bnzm1cd) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/e8da9995c611a56679f1609c60f40012cce65ee9/README.md#L168)):*
> ```
> Sometimes you may need to rebase your changes, e.g. when fixing a mistake in your commit. The default
> `git rebase` command discards the empty merge commits, so use `git rebase -i --rebase-merges [commit]`
> to preserve them.
> ```
Good to mention, I wasn't aware of that :-)

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-flux/3)* status: all files reviewed, 4 unresolved discussions (waiting on @haphut and @jschummer)

___
*[README.md, line 112 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MZIiVry2OWsNr8oKoIt:-MZMzUe63cCSzk4yt-G7:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/e8da9995c611a56679f1609c60f40012cce65ee9/README.md#L112)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
>  with a high confidence that at what
> ```
I think the "that at what" is maybe not so good English, also the "a" in "a high confidence" should probably go.

Would maybe something like "We should be able to pinpoint the time, stage, and version of what was deployed" work?

The "high confidence" can of course also be put back in there :-)
</blockquote></details>

Done.
___
*[README.md, line 132 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MZIiiP1Cvyrnd-g8pq0:-MZMzGXU4xFjy2Ax7LSw:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/e8da9995c611a56679f1609c60f40012cce65ee9/README.md#L132)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> do
> ```
"do" in the end not needed / artifact from previous version?
</blockquote></details>

Done.
___
*[README.md, line 139 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MZIipgz0kgED18wznJk:-MZMujPG0Pxn8wybdQ6e:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/e8da9995c611a56679f1609c60f40012cce65ee9/README.md#L139)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> no fast-forward
> ```
For clarity, maybe better to use an additional dash: "no-fast-forward"
</blockquote></details>

Done.
___
*[README.md, line 140 at r3](https://reviewable.io/reviews/hsldevcom/jore4-flux/3#-MZIiw8y18z4_n5Nds4Q:-MZMzf-i8gSJcHx9hUYb:b-ut4gmb) ([raw file](https://github.com/hsldevcom/jore4-flux/blob/e8da9995c611a56679f1609c60f40012cce65ee9/README.md#L140)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> testity of
> ```
Did you mean "testify" instead of "testity of"?
</blockquote></details>

testify about :)

**Pull request merged**
